### ISSUE TITLE
Use Sandstorm roles admin, owner, read, write

### ISSUE THREAD

**Issue by JamborJan** [JamborJan/paperwork#2]
Comment from https://groups.google.com/forum/#!topic/sandstorm-dev/iyV_HX_-eU8

>> - Make the paperwork instance sharable read-only, everybody who has the unique link can access it read only. Important: Grains created from older versions of the app are unfortunately not shareable.

>Yay. I see you're basing this on X-Sandstorm-Permissions, which is great. Keep in mind that once David finishes implementing sharing you may want to define separate permissions for "read" and "edit", so the hack of creating a dummy user might get more complicated.

I will try to implement some tests during the next weeks were I simulate "read" and "edit" with the sandstorm pkg file in my dev environment. I will add this as a issue in my github repo and include it for the next version of the app. I will also take care that data is right migrated if required. 

>    By the way, I looked at your usage of X-Sandstorm-{Username,User-Id} and have some comments there:
>    - I see you are putting X-Sandstorm-User-Id in the "password" field. Note that the user ID is not a secret, so you need to make sure that all normal password-based login paths are disabled for this to be safe. It might make sense to instead fill in the password randomly and store the user ID in a separate field. Or, better yet, it might make sense to get rid of Paperwork's entire user model. As long as you are enforcing permissions (via X-Sandstorm-Permissions), there's no need to keep track of users.

As far as I can see I have to use at least dummy user in the system which equal the available permissions. A login should not be possible, I will check the login paths once again in more detail for the next version of the app.
 
>    - I see you are using X-Sandstorm-Username as the username field in the database. Watch out, because X-Sandstorm-Username is not unique -- it's usually just the user's full name, and multiple people (or, more commonly, multiple accounts belonging to the same person) can have the same name. We probably should have named it "X-Sandstorm-Display-Name" instead.

I'm maybe changing that also to be named like the roles (admin, owner, edit, read or so). I'm not sure if sandstorm will later allow to hand over a grain to someone else and the original owner will be removed from the access entirly. In that case the name of the original owner makes no sense in the database. I add this also to my backlog for the next version of the app.

**Comment by kentonv** [comment]
FWIW, I recommend having three roles called "owner" (manage+write+read), "editor" (write+read), and "viewer" (read). This is a bit more approachable for non-technical users.

**Comment by JamborJan** [comment]
See https://github.com/dwrensha/gitweb-sandstorm/commit/7f510ec82a935a9f94ebcf9651983d0bbadcf82a

**Comment by JamborJan** [comment]
Hi @paulproteus,

can you help me with some ideas about how to best implement the role / sharing model of sandstorm. 

I have created these permissions (https://github.com/JamborJan/paperwork/blob/master/.sandstorm/sandstorm-pkgdef.capnp#L74-L77):
- admin (create new notes, notebooks, keywords, edit this stuff)
- edit (only edit existing notes, nothing to be created)

I have these roles (https://github.com/JamborJan/paperwork/blob/master/.sandstorm/sandstorm-pkgdef.capnp#L74-L77):
- Editor (true, true)
- Viewer (false, false)
- Commenter (false, true)

Sharing with these works quite well:
![bildschirmfoto 2015-06-15 um 20 15 16](https://cloud.githubusercontent.com/assets/7508960/8166943/5c50631e-139b-11e5-9542-7059e7bd0a83.png)

In Paperwork I need at least one user which I create when setting up the grain. I also create a dummy user for public sharing (no sandstorm user). See this: https://github.com/JamborJan/paperwork/blob/master/frontend/app/controllers/UserController.php#L116

Everything is still a bit buggy and not 100% worked through but it basically gives an impression what is intended. The big thing here is now: I have to edit the original code from Paperwork in several parts to add the „if sandstorm“ part and depending on that decide if certain stuff is displayed or removed from the UI. E.g. https://github.com/JamborJan/paperwork/blob/master/frontend/app/views/templates/paperworkNoteShow.blade.php#L27-L35

What do you think? Does it make sense that way? Or is there a more sustainable approach which might get a chance to be merged upstream one day? (I know nothing you decide but maybe you can say something from your experience in open source projects).

Thanks a lot for your help. My goal is to create this Paperwork package in a way you guys planned to have the packages working so that others can see how it is done here and can reuse the methodology.

**Comment by paulproteus** [comment]
Hi @JamborJan !

Some general thoughts for you.

## On app permissions generally

For getting apps to respect Sandstorm permissions, there are generally two ways to achieve this.

1. *Statefully store the permissions information into the app's user database.* This is basically what you're doing now. One theoretical difficulty of this approach is that if the `X-Sandstorm-Permissions` for a user change (because the user got some new permissions), you will need to make sure to update the app's user database. I think you're not doing that, if I'm reading this code correctly.

2. *Statelessly use the information in the request to calculate permissions.* I personally don't recommend this for apps that weren't build with Sandstorm in mind, but in theory you could ignore the user database.

You're doing option 1, which is the only one I've actually seen anyone use in a Sandstorm package, so I think that's the best way. I think you'll need to do some more work to make sure that any _changes_ to the Sandstorm permissions flow into the Paperwork users that you're creating.

## Location of code changes

It's nice to be able to make Sandstorm-related code changes in as few places as possible.

In the case of user creation, you're taking code that used to print HTML (specifically, used to print the login box) and replacing it with code that causes a database query. I find that a little odd. I wonder if you can do the database query (and the logging the user in) at some other point in the app's code path. Perhaps some part that gets executed before the visual elements get rendered.

## Add an is_sandstorm setting to the Paperwork settings

Eventually, I hope you'll consider upstreaming these changes. Given that goal, it's important that the Sandstorm-related things can be enabled/disabled easily, and that disabling the Sandstorm-related features disables them totally.

I noticed that your code always trusts the `X-Sandstorm-Permissions` header. This is safe on Sandstorm, but not safe on the public web. One thing you can do is to create a setting in e.g this file https://github.com/twostairs/paperwork/blob/master/frontend/app/config/app.php that is `$is_sandstorm=true;`.

Then, you can check, e.g.

```
if ($is_sandstorm) {
    // Do the user creation etc. stuff
}
```

As for making sure the login box doesn't display, because it is meaningless on Sandstorm, you could do something like the following in https://github.com/JamborJan/paperwork/blob/master/frontend/app/controllers/UserController.php#L113

```
// If we are on Sandstorm, do not show the login boxes since the user is already logged in.
if ($is_sandstorm) {
    return;
}
```

I don't know if upstream will _love_ that, but they might be OK with it. Compared to what you're doing now, it has the upside that no code is _deleted_, so the same codebase can run properly on Sandstorm and non-Sandstorm.

A different thing they might prefer is if you use CSS to `display: none;` the visual elements that aren't needed. One way to do that is to create a `sandstorm.css` file, and find the selectors to match the elements you want to hide, and hide them. (Or add a CSS class to them called `hide-on-sandstorm`.) I think the choice between these depends on upstream's preferences, but they'll basically always want one codebase that works properly on Sandstorm & on non-Sandstorm, dispatched on a `frontend/app/config/` setting.

(Note: It might not be literally `if ($is_sandstorm)` -- it might be more like `Config::get('paperwork.is_sandstorm')`)

**Comment by JamborJan** [comment]
Done with https://github.com/JamborJan/paperwork/pull/16

Including all the useful feedback from @paulproteus thanks for that!
